# version: '3.8'

services:
  db:
    image: postgres:15
    container_name: weather_db
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # 1. The LIVE data (Fast, Local, NOT Synced)
      # This lives inside your laptop's internal storage for speed.
      - postgres_data:/var/lib/postgresql/data
      
      # 2. The BRIDGE to Google Drive
      # This maps your cloud folder to "/app/cloud_data" inside the container.
      # We will use this to read your Excel file and write backups.
      - ~/GoogleDrive/weather_data:/app/cloud_data
    ports:
      - "5432:5432"
    restart: unless-stopped

    # (Optional) Installs a health check to verify DB is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d weather_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/app
      - ~/GoogleDrive/weather_data:/app/cloud_data
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
